config/routes.rb
Rails.application.routes.draw do
  # get 'tags/title'
  devise_for :users
  root to: "pages#home"
  get "my_buddies", to: "pages#my_buddies"


  resources :buddies, only: %i[index show] do
    # resources :messages, only: %i[create]
    resources :reviews, only: %i[new create]
  end

  resources :chats, only: %i[index create show] do
    resources :messages, only: %i[create]
  end

  resources :profiles, only: %i[show index] do
    resources :buddies, only: %i[new create]
  end

  resources :locations, only: %i[index show]

  # resources :users, only: :show do
  # resources :reviews, only: [:new, :create]
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  belongs_to :asker, class_name: "User"
  belongs_to :receiver, class_name: "User"
  has_many :reviews
  validates_uniqueness_of :asker, scope: [:receiver]

  enum status: [:accepted, :rejected, :pending]
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
  belongs_to :user_a, class_name: "User"
  belongs_to :user_b, class_name: "User"
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :sender, class_name: "User"

  def sender?(a_user)
    sender.id == a_user.id
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :buddy
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :user_tags
  has_many :users, through: :user_tags

  # include PgSearch::Model
  # pg_search_scope :search_by_title,
  # against: [ :title ],
  # using: {
  #   tsearch: { prefix: true } # <-- now `superman batm` will return something!
  # }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :chats
  has_many :messages


  has_many :displaced_buddies, class_name: "Buddy", foreign_key: :asker_id, dependent: :destroy
  has_many :local_buddies, class_name: "Buddy", foreign_key: :receiver_id, dependent: :destroy

  has_one_attached :photo
  has_many :user_tags
  has_many :reviews
  has_many :tags, through: :user_tags

  # :user_tags, :buddys,:language_tags

  has_many :reviews, dependent: :destroy

  # Find all user's buddies
  def my_buddies
    if displaced
      local_buddies
    else
      displaced_buddies
    end
  end

  # def my_pending_requests
  #   buddies_as_receiver.where(status: :pending)
  # end
end


# Create status field on Buddy
# set status field as enum for buddy, :accepted, :rejected, :pending
# when a buddy is created, automaitcally set it to pending
# create pending request view so a receiver can have a list of pending buddies to accept / reject them
# when finding a user's buddies, filter for only accepted buddies

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[displaced lockable])
  end
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  def index
    @buddies = Buddy.where(asker_id: current_user.id).or(Buddy.where(receiver_id: current_user.id))
    @users_ids = []
    @buddies.each do |buddy|
      if buddy.asker_id == current_user.id
        bud = buddy.receiver_id
      else
        bud = buddy.asker_id
      end
      @users_ids << bud
    end
    @users = []
    @users_ids.each do |id|
      user = User.find(id)
      @users << user
    end
    @users
  end

  def show
    @buddy = Buddy.find(params[:id])
  end

  def new
    @buddy = Buddy.new
  end

  def create
    @local_person = User.find(params[:profile_id])

      @buddy = Buddy.new
      @buddy.receiver = @local_person
      @buddy.asker = current_user
      @buddy.status = "pending"
      if @buddy.save!
        redirect_to buddies_path
      else
        render new, notice: 'Buddy not created'
      end

  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  
    @chats = Chat.where(user_a:current_user).or(Chat.where(user_b:current_user))
  end

  def show
    @chat = Chat.find(params[:id])
    @message = Message.new
  end

  def create
    @user_b = User.find(params[:profile_id])
    @chat = Chat.new(name: "#{current_user.name} & #{@user_b.name} Chat")
    @chat.user_a_id = current_user.id
    @chat.user_b_id = @user_b.id
    redirect_to chat_path(@chat) if @chat.save!
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if params[:query].present?
      @locations = Location.where("category LIKE ?", "%#{params[:query]}%")
    else
      @locations = Location.all
    end

    # The `geocoded` scope filters only locations with coordinates
    @markers = @locations.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        info_window: render_to_string(partial: "info_window", locals: {location: location}),
        image_url: helpers.asset_url("https://res.cloudinary.com/dbgvo56a1/image/upload/v1662397564/Pin_hwnomy.svg")
      }
    end
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chat = Chat.find(params[:chat_id])
    @message = Message.new(message_params)
    @message.chat = @chat
    @message.sender_id = current_user.id
    if @message.save
      ChatChannel.broadcast_to(
        @chat,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.sender_id
      )
      head :ok
    else
      render "chats/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @disable_nav = true
  end

  # def my_buddies
  #   @my_buddies = current_user.buddies
  # end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    sleep 3
    @profiles = User.all

    if params[:query].present?

      if current_user.displaced
        @profiles = User.joins(:tags).where("tags.title ILIKE ?", "%#{params[:query]}%").where(displaced: false)
      elsif current_user.displaced == false
        @profiles = User.joins(:tags).where("tags.title ILIKE ?", "%#{params[:query]}%").where(displaced: true)
      else
        @profiles = User.all
      end
    else
      if current_user.displaced
        @profiles = User.where(displaced: false)
      elsif current_user.displaced == false
        @profiles = User.where(displaced: true)
      else
        @profiles = User.all
      end
    end

  end

  def show
    @profile = User.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # @user = User.find(params[:buddy_id])
    @buddy = Buddy.find(params[:buddy_id])
    @review = Review.new
    # @review.buddy = @buddy
    # @review.user = current_user
  end

  def create
    @review = Review.new(review_params)
    @buddy = Buddy.find(params[:buddy_id])
    @review.buddy = @buddy
    if @buddy.asker_id == current_user.id
      @review.user = User.find(@buddy.receiver_id)
    else
      @review.user = User.find(@buddy.asker_id)
    end

    if @review.save
      redirect_to buddies_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buddies/index.html.erb
<div class="container py-3" data-controller="readmore">
  <h1>My buddies</h1>


  <% @users.each do |profile| %>

    <div class="scene scene--card-giva mt-3">

      <div class="card-giva">

          <div class="card__face card__face--front">

            <div class="wrapper-div-front">

              <div class="padding-div">
              </div>

              <div class="content-wrapper-front">

                <div class="avatar-wrapper">
                  <%= link_to profile_path(profile) do %>
                  <% if profile.displaced %>
                    <%= cl_image_tag profile.photo.key, class:"avatar" %>
                  <% else %>
                    <%= cl_image_tag profile.photo.key, class:"avatar" %>
                  <% end %>
                    <h1 class="avatar-name"><%=profile.name%><h1>
                  <% end %>
                </div>

                <div class="hand-wrapper">

                  <% if profile.displaced %>
                    <div class="hand">Need a hand with</div>
                    <div class="hand-content">
                      <%= profile.problem %>
                    </div>
                  <% else %>
                    <div class="hand">Give a hand with</div>
                    <div class="hand-content">
                      <%= profile.problem %>
                    </div>
                  <% end %>

                </div>


                <div class="hand-wrapper">
                <div class="hand">Tags</div>
                  <div class="tag-wrapper">
                    <% profile.user_tags.each do |dbTag| %>
                        <span class="tag"><%= Tag.find(dbTag.tag_id).title %></span>
                    <% end %>
                  </div>
                </div>

              </div>

              <div class="arrow-right">
                <img src="https://res.cloudinary.com/dbgvo56a1/image/upload/v1662386125/arrow-right_jxhaee.png" alt="">
              </div>

            </div>

          </div>



          <div class="card__face card__face--back">

            <div class="wrapper-div-back">

              <div class="arrow-left">
                <img src="https://res.cloudinary.com/dbgvo56a1/image/upload/v1662386125/arrow-left_b0rgmu.png" alt="">
              </div>

              <div class="content-wrapper-back">

                <div class="hand-wrapper">
                  <div class="my-bio">About me</div>
                  <div class="bio">
                    <%= profile.bio %>
                  </div>
                </div>

                <div class="hand-wrapper">
                  <% if profile.reviews.count == 0 %>
                    <div class="hand">No feedback of <%=profile.name%> yet</div>
                  <% else %>
                    <div class="hand">Feedback of <%=profile.name%></div>
                  <% end %>
                    <div class="review">
                        <% profile.reviews.each do |review| %>
                          <div class="reviews">
                            <%= ["😖","😕","🙂","😊","🥰"][(review.rating - 1)] if review.rating %> <%= review.content %>

                          </div>
                        <% end %>
                    </div>
                </div>




                <div class="button-wrapper">

                  <% chat = Chat.where(user_a_id: current_user.id, user_b_id: profile.id) || Chat.where(user_a_id: profile.id, user_b_id: current_user.id) %>
                  <% unless chat.empty? %>
                    <%= link_to "Chat", chat_path(chat[0].id), data: {turbo_method: :get}, class:"chat-button" %>
                  <% else %>
                    <%= link_to "Chat", chats_path(profile_id: profile.id), data: {turbo_method: :post}, class:"chat-button" %>
                  <% end %>

                  <% buddies = Buddy.where(asker_id: current_user.id, receiver_id: profile.id) || Buddy.where(asker_id: profile.id, receiver_id: current_user.id) %>

                  <%= link_to "Review", new_buddy_review_path(buddies.first.id), class:"buddy-button" %>


                </div>

              </div>

              <div class="padding-div">
              </div>

            </div>

          </div>

      </div>
    </div>
  <% end %>
</div>

app/views/buddies/new.html.erb
<h1>New#Buddies</h1>

app/views/buddies/show.html.erb
<h1>Show#buddies</h1>

app/views/chats/index.html.erb
<div class="">
  <% @chats.each do |chat| %>
    <%= link_to chat_path(chat) do%>
      <div class="px-3 py-2">
        <% if chat.user_a == current_user %>
          <div class="d-flex justify-content-start align-items-center">
            <% if chat.user_b.photo.attached? %>
              <%= cl_image_tag chat.user_b.photo.key, class: "chatindex-avatar" %>
            <% end %>
            <div class="ps-3 flex-grow-1 d-flex justify-content-between align-itmes-start">
              <div class="flex-grow-1">
                <h3 class="chatindex-avatar-name"><%=chat.user_b.name%></h3>
                <p class="pt-2"><%=chat.messages.last.content unless chat.messages.empty? %><p>
              </div>
              <div class="text-center">
                <p class="chat-time"><%=chat.messages.last.created_at.strftime("%H:%m") unless chat.messages.empty? %></p>
                <% if !chat.messages.empty? %>
                  <div class="d-flex justify-content-center pt-2">
                    <div class="green-dot"></div>
                  </div>
                <% end %>
              </div>
            </div>

          </div>
        <% else %>
          <div class="d-flex justify-content-start align-items-center">
            <% if chat.user_a.photo.attached? %>
              <%= cl_image_tag chat.user_a.photo.key, class: "chatindex-avatar" %>
            <% end %>
            <div class="ps-3 flex-grow-1 d-flex justify-content-between align-itmes-start">
              <div class="flex-grow-1">
                <h3 class="chatindex-avatar-name"><%=chat.user_a.name%></h3>
                <p class="pt-2"><%=chat.messages.last.content unless chat.messages.empty? %><p>
              </div>
              <div class="text-center">
                <p class="chat-time"><%=chat.messages.last.created_at.strftime("%H:%m") unless chat.messages.empty? %></p>
                <% if !chat.messages.empty? %>
                  <div class="d-flex justify-content-center pt-2">
                    <div class="green-dot"></div>
                  </div>
                <% end %>
              </div>
            </div>

          </div>
        <% end %>
      </div>
    <% end %>

  <% end %>

</div>

app/views/chats/show.html.erb
<div class="container chatroom"
  data-controller="chat"
  data-chat-chat-id-value="<%= @chat.id %>"
  data-chat-current-user-id-value="<%= current_user.id %>">



  <div class="messages" data-chat-target="messages">
    <% @chat.messages.each do |message| %>
    <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
      <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
        <%= render "messages/message", message: message %>
      </div>
    </div>
    <% end %>
  </div>


<div class="chataction">
  <%= simple_form_for [@chat, @message],
  html: { data: { action: "turbo:submit-end->chat#resetForm" }, class: "d-flex" } do |f|
  %>
    <%= f.input :content,
      label: false,
      # placeholder: "Message ##{@chat.name}",
      wrapper_html: {class: "flex-grow-1 rounded-20px chatEl"}

    %>
    <%= f.submit "Send", class: "mb-3 p-2 send-minty" %>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-controller="navigation">
  <head>
    <title>GivA</title>
    <link rel="icon" type="image/png" href="<%= image_path("favicon.png") %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css' rel='stylesheet' />

  </head>


  <body class="" style="height: 100vh;">
    <% if params[:controller] == 'chats' && params[:action] == 'show' %>
         <%= render "shared/chatbar", chat: @chat %>
    <% else %>
      <%= render "shared/navbar" unless @disable_nav %>
    <% end %>
    <div class="overflow-scroll <%= params[:action] == 'home' ? 'bgrwhite' : 'bgrcolor' %>" style="height: <%= params[:action] == 'home' ? '100vh' : '90vh' %>;">
      <%= yield %>
    </div>
    <%= render "shared/flashes" %>
    <%= render "shared/tabbar" unless @disable_nav %>
  </body>
</html>

app/views/locations/_info_window.html.erb
 <div class="fonts">
  <h2><%= location.category %></h2>
  <p><%= location.description %></p>
  <p>Address : <%= location.address %></p>
  <p>Opening hours : <%= location.opening_hour.strftime("%H:%M") %> - <%= location.closing_hour.strftime("%H:%M") %></p>
 </div>
git

app/views/locations/index.html.erb
  <%= form_with url: locations_path, method: :get, class: "d-flex search-bar justify-content-between m-3" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "w-100 flex-grow-1 search-input",
      placeholder: "Find a location"
    %>
    <%= submit_tag "Search", class: "search-button" %>
  <% end %>

  <div class="pb-5 mb-5" style="width: 100%; height: 87%;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

app/views/pages/home.html.erb
<div class="container bgrwhite">
  <div class="logo" data-controller="logo-rotate">
    <%= link_to profiles_path do %>
      <%= image_tag "https://res.cloudinary.com/dbgvo56a1/image/upload/v1662390189/logo_landingpage_inl4uc.svg",
        width: 250, height: 250, crop: :fill, class: "before-rotate", data: { action: "click->logo-rotate#rotate", "logo-rotate-target": "logo" } %>
    <% end %>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="container bgrcolor" data-controller="readmore">
  <%= form_with url: profiles_path, method: :get, class: "d-flex search-bar justify-content-between m-3" do %>

    <%= text_field_tag :query,
      params[:query],
      class: "search-input w-100",
      placeholder: "Search for tags"
    %>
    <%= submit_tag "Search", class: "search-button" %>
  <% end %>
<h1>Buddies nearby</h1>
  <% @profiles.each do |profile| %>

    <div class="scene scene--card-giva my-3">

      <div class="card-giva">

          <div class="card__face card__face--front">
            <div class="wrapper-div-front">

              <div class="padding-div">
              </div>

              <div class="content-wrapper-front">

                <div class="avatar-wrapper">
                  <%= link_to profile_path(profile) do %>
                    <% if profile.displaced %>
                      <%= cl_image_tag profile.photo.key, class:"avatar" %>
                    <% else %>
                      <%= cl_image_tag profile.photo.key, class:"avatar" %>
                    <% end %>
                    <h1 class="avatar-name"><%=profile.name%><h1>
                  <% end %>
                </div>

                <div class="hand-wrapper">

                  <% if profile.displaced %>
                    <div class="hand">Need a hand with</div>
                    <div class="hand-content">
                      <%= profile.problem %>
                    </div>
                  <% else %>
                    <div class="hand">Give a hand with</div>
                    <div class="hand-content">
                      <%= profile.problem %>
                    </div>
                  <% end %>

                </div>

                <div class="hand-wrapper">
                <div class="hand">Tags</div>
                  <div class="tag-wrapper">
                    <% profile.user_tags.each do |dbTag| %>
                        <span class="tag"><%= Tag.find(dbTag.tag_id).title %></span>
                    <% end %>
                  </div>
                </div>
              </div>

              <div class="arrow-right">
                <img src="https://res.cloudinary.com/dbgvo56a1/image/upload/v1662386125/arrow-right_jxhaee.png" alt="">
              </div>

            </div>
          </div>



          <div class="card__face card__face--back">

            <div class="wrapper-div-back">

              <div class="arrow-left">
                <img src="https://res.cloudinary.com/dbgvo56a1/image/upload/v1662386125/arrow-left_b0rgmu.png" alt="">
              </div>

              <div class="content-wrapper-back">

                <div class="bio-wrapper">
                  <div class="my-bio">About me</div>
                  <div class="bio">
                    <%= profile.bio %>
                  </div>
                </div>

                <% unless profile.reviews.empty? %>
                  <div class="hand-wrapper">
                    <div class="hand">Feedback of <%=profile.name%></div>
                      <div class="review">
                          <% profile.reviews.each do |review| %>
                            <div class="reviews">
                            <%= ["😖","😕","🙂","😊","🥰"][(review.rating - 1)] if review.rating %> <%= review.content %>
                            <%=%>
                            </div>
                          <% end %>
                    </div>
                  </div>
                  <% else %>
                  <div class="hand">No feedback of <%=profile.name%> yet</div>
                  <% end %>

                <div class="button-wrapper">
                  <% chat = Chat.where(user_a_id: current_user.id, user_b_id: profile.id) || Chat.where(user_a_id: profile.id, user_b_id: current_user.id) %>
                  <% unless chat.empty? %>
                    <%= link_to "Chat", chat_path(chat[0].id), data: {turbo_method: :get}, class:"chat-button" %>
                  <% else %>
                    <%= link_to "Chat", chats_path(profile_id: profile.id), data: {turbo_method: :post}, class:"chat-button" %>
                  <% end %>
                  <% buddies = Buddy.where(asker_id: current_user.id, receiver_id: profile.id) || Buddy.where(asker_id: profile.id, receiver_id: current_user.id) %>
                  <% if buddies.empty? %>
                    <%= link_to "Buddy Up", profile_buddies_path(profile_id: profile.id), data: {turbo_method: :post}, class:"buddy-button" %>
                  <% else %>
                    <%= link_to "Review", new_buddy_review_path(buddies.first.id), class:"buddy-button" %>
                  <% end %>
                </div>

              </div>

              <div class="padding-div">
              </div>

            </div>

          </div>

      </div>

    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<%# basically a card on one page (front+back combined + reviews) %>


      <div class="wrapper-div-show">

        <div class="content-wrapper-front-show">

          <div class="avatar-wrapper">
            <% if @profile.displaced %>
              <%= cl_image_tag @profile.photo.key, class:"avatar" %>
            <% else %>
              <%= cl_image_tag @profile.photo.key, class:"avatar" %>
            <% end %>
              <h1><%=@profile.name%><h1>
          </div>

          <div class="hand-wrapper-show">

            <% if @profile.displaced %>
              <div class="hand">Need a hand with</div>
              <div class="hand-content">
                <%= @profile.problem %>
              </div>
            <% else %>
              <div class="hand">Give a hand with</div>
              <div class="hand-content">
                <%= @profile.problem %>
              </div>
            <% end %>

          </div>

          <div class="bio-wrapper">
            <div class="my-bio">About me</div>
              <div class="bio-show">
                <%= @profile.bio %>
              </div>
          </div>

          <div class="tag-wrapper">
            <% @profile.tags.each do |tag| %>
              <span class="tag"><%= tag.title %></span>
            <% end %>
          </div>

          <% unless @profile.reviews.empty? %>
                  <div class="hand-wrapper">
                    <div class="hand">Feedback of <%=@profile.name%></div>
                      <div class="review">
                          <% @profile.reviews.each do |review| %>
                            <div class="reviews">
                            <%= ["😖","😕","🙂","😊","🥰"][(review.rating - 1)] if review.rating %> <%= review.content %>
                            <%=%>
                            </div>
                          <% end %>
                    </div>
                  </div>
                  <% else %>
                  <div class="hand">No feedback of <%=@profile.name%> yet</div>
                  <% end %>



          <div class="button-wrapper">
            <% chat = Chat.where(user_a_id: current_user.id, user_b_id: @profile.id) || Chat.where(user_a_id: @profile.id, user_b_id: current_user.id) %>
            <% unless chat.empty? %>
              <%= link_to "Chat", chat_path(chat[0].id), data: {turbo_method: :get}, class:"chat-button" %>
            <% else %>
              <%= link_to "Chat", chats_path(profile_id: @profile.id), data: {turbo_method: :post}, class:"chat-button" %>
            <% end %>
            <% buddies = Buddy.where(asker_id: current_user.id, receiver_id: @profile.id) || Buddy.where(asker_id: @profile.id, receiver_id: current_user.id) %>
                  <% if buddies.empty? %>
                    <%= link_to "Buddy Up", profile_buddies_path(profile_id: @profile.id), data: {turbo_method: :post}, class:"buddy-button" %>
                  <% else %>
                    <%= link_to "Review", new_buddy_review_path(buddies.first.id), class:"buddy-button" %>
                  <% end %>
          </div>

        </div>

      </div>

app/views/reviews/new.html.erb
<%# <%= simple_form_for (@profile @review) %>
<div class="scene scene--card-giva mt-3">
  <div class="card-giva">
    <div class="card__face card__face--front">
      <div class="wrapper-div-front">
            <div class= "rating", style="">
              <h2>How was your experience with your buddy <%= @buddy.receiver.name || @buddy.receiver.email %>?</h2>
              <br>
                <%= simple_form_for [@buddy, @review] do |f| %>
                  <div class="hand"><%= f.label :rating, 'Rate your Buddy' %></div>
                <p>
                    😖 <%= f.radio_button :rating, 1, class: "radio"%>
                    😕 <%= f.radio_button :rating, 2, class: "radio" %>
                    🙂 <%= f.radio_button :rating, 3, class: "radio" %>
                    😊 <%= f.radio_button :rating, 4, class: "radio" %>
                    🥰 <%= f.radio_button :rating, 5, class: "radio" %>
                </p>

              <%#= simple_form_for :url => profile_reviews_path(current_user), :method => :post do |f| %>
                <div class="hand"><%= f.input :content, placeholder: "Comment on how you found your buddy..." %></div>
                <%= f.submit 'Post feedback', class: 'submit-button'%>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>`

app/views/shared/_chatbar.html.erb
<div class="chatbar-giva d-flex justify-content-between align-items-center chat-container-fluid w-100">
  <div class="">
    <%= link_to chats_path do %>
    <img src="https://res.cloudinary.com/dbgvo56a1/image/upload/v1662557382/arrow-left-white_zkgi5y.svg" alt="">
    <% end %>
  </div>

    <% if chat.user_a == current_user %>
      <h1 class="chat-avatar-name pe-3"><%=chat.user_b.name%><h1>
    <% else %>
      <h1 class="chat-avatar-name pe-3"><%=chat.user_a.name%><h1>
    <% end %>

  <div>
    <% chat_partner = chat.user_a == current_user ? chat.user_b : chat.user_a %>
    <%= link_to profile_path(chat_partner) do %>
      <% if chat.user_a == current_user %>
        <%= cl_image_tag chat.user_b.photo.key, class:"chat-avatar" %>
      <% else %>
        <%= cl_image_tag chat.user_a.photo.key, class:"chat-avatar" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_tabbar.html.erb
<footer class="footer mt-auto position-absolute w-100" style="bottom:0;">
  <div class="footer-links">

    <%= active_link_to '<i class="fa-solid fa-address-book"></i>'.html_safe, profiles_path, class_active: 'back-active'%>

    <%= active_link_to '<i class="fa-solid fa-comment"></i>'.html_safe, chats_path,  class_active: 'back-active'%>

    <%= active_link_to '<i class="fa-solid fa-map-location-dot"></i>'.html_safe, locations_path,  class_active: 'back-active'%>

    <%= active_link_to '<i class="fa-solid fa-hand-holding-hand"></i>'.html_safe, buddies_path,  class_active: 'back-active'%>
  </div>
</footer>